language: go

go:
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip


before_install:
  - eval "$(ssh-agent -s)"
  # we only decrypt the SSH key when we aren't in a pull request 
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/install_key.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export SSH_AUTH_SOCK="" ; fi'
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis CI"

install:
  - rm -rf $GOPATH/src/gopkg.in/src-d
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - ln -s $PWD $GOPATH/src/gopkg.in/src-d/go-git.v4
  - cd $GOPATH/src/gopkg.in/src-d/go-git.v4
  - go get -v -t ./...

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
