language: go

go:
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip


before_install:
  - openssl aes-256-cbc -K $encrypted_1477e58fe67a_key -iv $encrypted_1477e58fe67a_iv -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy.pem
  - ssh-add .travis/deploy.pem

install:
  - rm -rf $GOPATH/src/gopkg.in/src-d
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - ln -s $PWD $GOPATH/src/gopkg.in/src-d/go-git.v4
  - cd $GOPATH/src/gopkg.in/src-d/go-git.v4
  - go get -v -t ./...

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
